### ISSUE TITLE
劫持jd.com到垃圾广告网站

### ISSUE THREAD

**Issue by pkuoliver** [teocci/JSONViewer-for-Chrome#14]
为你感到羞耻

**Comment by teocci** [comment]
an you use "https://global.jd.com" instead. I will fix this ....

**Comment by 582033** [comment]
浪费了7天时间去排除插件, 最后发现是这个李鬼的 jsonview

**Comment by macouen** [comment]
shame on you！！！

**Comment by teocci** [comment]
Shame? why? this is an open source you can roll back to the the version 0.8.13 or 0.8.7. I also I put a disclaimer saying that the script is running.  What is the same? Here is the Disclaimer if you didn't notice it.


Disclaimer
==========

Last updated: December 09, 2017

The content shown for the JSONViewer Google Chrome Extension (the "Service")
is for general use only.

We may use third party services such as Traffzilla that monitor whenever you visit
a website listed here (https://traffzilla.xyz/coverage?key=4d4d2708f61508192a1c4da6b238cc4c)

Log Data

We want to inform you that our Service may contain a Traffzilla script. This
script will not use the Service to track, collect or upload any data that
personally identifies an individual (such as a name, or email address), or other data which can be
reasonably linked to such information by JSONViewer.

**Comment by michaelhart** [comment]
My personal complaint with the updates to JSON Viewer is that the update was automatically pushed and enabled on the computers of over 39,000 users, logging private search and browsing activity to "traffzilla.xyz". Updating the description is not a sufficient form of notification in becoming spyware.

I fully support your desire to monetize your extension, but not at the expense of my data. For anyone else seeking alternatives, [this](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=en) seems like a great one.

**Comment by teocci** [comment]
Excuse me? logging private search and browsing activity? I'm sorry but this is an open source extension. You can check the code where in the code I'm logging private search and browsing activity??/ You are committing slander, even saying that is a spyware?

For instance, here is the main core of the referral code:

        if (found) {
            link =
                apiUrl +
                '/get?key=' +
                sourceId +
                '&out=' +
                encodeURIComponent(out) +
                '&ref=' +
                encodeURIComponent(out) +
                '&uid=&format=go';
            // console.log('Redirect URL: ', link);
        } else {
            // console.log("Domain not in coverage, set double pause",doc_domain);
            urls.data.used_domains[doc_domain] = adv_time + 86400000;
        }

What this does is: if your URL in in the URL List that it is in the Disclaimer,  then the script sends the URL to the Traffzilla and then Traffzilla redirects it to the URL site. Is that  logging private search and browsing activity???

When they contact me they said that the redirection is not intrusive and clean for the user, and the users will not have any problem. I tested for 4 days in my own environment and I thought that it was OK.

These kind of statements are wrong this is not an spyware, this is a simple extension that shows its source and you can decide if you keep it or not.

**Comment by teocci** [comment]
Also as I promised the Traffzilla will be removed on Dec 22, 2017.
