### ISSUE TITLE
何止京东, 还有很多网站

### ISSUE THREAD

**Issue by 582033** [teocci/JSONViewer-for-Chrome#15]
触发劫持的列表在下面,
https://traffzilla.xyz/coverage?key=4d4d2708f61508192a1c4da6b238cc4c

这些都会跳转到 href.li 然后然后再跳到垃圾广告网站, 一定要注意这个李鬼jsonviwer , 正牌是jsonview.

**Comment by michealzh** [comment]
我说呢 扩展一开各种瞎跳

**Comment by teocci** [comment]
Traffzilla was removed
