### ISSUE TITLE
Traffzilla interfering with other websites

### ISSUE THREAD

**Issue by DHandspikerWade** [teocci/JSONViewer-for-Chrome#16]
Traffzilla appears to be causing issues with links on other websites. The issue creates a blank page with the domain of traffzilla.xyz after clicking a cross domain link. I had noticed the issue while trying to logging into my banks website. This caused the username and password to be POST'ed to this third-party domain.

**Comment by JonAbrams** [comment]
This problem is the only reason I discovered that this extension was secretly tracking all my web traffic.

**Comment by DHandspikerWade** [comment]
@JonAbrams If the extension is actually packed based on this repo, it was only added recently (https://github.com/teocci/JSONViewer-for-Chrome/pull/9). 

It's easy enough to remove it and reinstall as a new extension. The maintainer doesn't appear to be trying to hide the use of Traffzilla. The Chrome store has a pretty large paragraph in the description saying that it was added. It seems super sketchy to track all visited websites; even more so when there is seemly no public information about Traffzilla. Their website is just a Russian "Coming soon" site.

**Comment by teocci** [comment]
I was contacted by this russian company saying that this traffzilla it is clean and unnoticeable for the user. I check the code and as they said only redirect when you access to one of the listed pages. I think I will remove this traffzila is only giving me headaches.

**Comment by teocci** [comment]
Traffzilla was removed in the version 0.8.13

**Comment by teocci** [comment]
Hey guys T_T I cant remove the script until Dec 26th T_T. You can compile the version 0.8.13 or 0.8.7 in the meanwhile. T_T Sorry guys I don't have money to refund that company the  issue will b open until that day T_T  Sorry again guys

**Comment by JonAbrams** [comment]
Thanks for the honesty. I've switched to: https://github.com/tulios/json-viewer

**Comment by DHandspikerWade** [comment]
Fair enough, I just packaged 0.8.7 for the time being and probably switch back later after this gets sorted out.
