### ISSUE TITLE
The extension is broken

### ISSUE THREAD

**Issue by darksabrefr** [teocci/JSONViewer-for-Chrome#27]
Hello,
The recent changes in this Google Chrome extension have broken almost everything :
- The JSON is formatted in less of than 1% of the loads, the init function doesn't seam to be called
- Custom themes are now simply ignored
- The collapse block event is triggered everywhere, and not only by clicking on the collapse button
- There's console.log everywhere

Please revert the last week changes and republish the previous and usable version !

**Comment by teocci** [comment]
The extension was updated to the manifest version 3. Now it is working again.
