### ISSUE TITLE
How many of packages do you actually ship? Which one is a working copy?

### ISSUE THREAD

**Issue by wzup** [teocci/JSONViewer-for-Chrome#3]
I have at least three of your plugins installed. Neither one has a Chrome Store page. Today the stopped folding the code:

In my Chrome Extension Manager
![extensions - google chrome 2016-12-18 09 05 13](https://cloud.githubusercontent.com/assets/3880497/21290754/9bca19e0-c501-11e6-8774-ef8afb29084d.png)

When View your extension in store
![error 404 not found 1 - google chrome 2016-12-18 09 06 43](https://cloud.githubusercontent.com/assets/3880497/21290756/a5876488-c501-11e6-80c1-4051fb0d9ba0.png)

Which version is correct?
Why code folding doesn't work?

**Comment by teocci** [comment]
Hey wzup.

Thanks for adding my extension. I see that you have another developers
versions. I recommend you to delete all of them and keep this one
https://goo.gl/QWWes1.

Have a good day and best regards.

*Teocci*
*Programmer & Web App Developer*
*99 Daehak-Ro, Yuseong-Gu, Daejeon, 305-764, South Korea*

*E-mail : jrfdeft@gmail.com <jrfdeft@gmail.com>*
