### ISSUE TITLE
I have noticed that the "Options" menu is disabled

### ISSUE THREAD

**Issue by quinefang** [teocci/JSONViewer-for-Chrome#7]
Could you please fix that? Sir

**Comment by teocci** [comment]
I tested in 4 different pc (2 windows, one ubuntu 16.04 and one Mac OS) and in all it works perfectly.

**Comment by quinefang** [comment]
Sir, please take a look at the [screenthost](https://drive.google.com/open?id=1FH8QsNgb1sNwQkfsDYlEnS-Ro3JUxHK0), what I mean is the "Options" button in the global menu of JSON Viewer on the most top right of Google Chrome is disabled, when I click on the JSON viewer's shortcut icon. 

It is very inconvenient that I have to browse a web page contains JSON content like [jsontest](http://headers.jsontest.com/) to enter the "JSONViewer options" page as seen in the [screenshot](https://drive.google.com/open?id=1kmqjMukZAKj8x5DWnKjIKlQa6XB8lQ7L), to change some related options.

It makes no sense that the "Options" button is always in disabled state. What about enable it or just remove it?

**Comment by quinefang** [comment]
I remember that the "Options" button was enabled by default in some previous versions of JSON Viewer, but I am not sure.

**Comment by teocci** [comment]
Interesting i will check why I think is a chrome security updates. I will reopen the issue and fix it asap

**Comment by quinefang** [comment]
Thank you

**Comment by teocci** [comment]
This was fixed in the version 0.8.9. Please update your extension.

**Comment by quinefang** [comment]
I have tested it and It worked just fine, thank you for your excellent job!
