### ISSUE TITLE
Traffzilla

### ISSUE THREAD

**Issue by timwhitlock** [teocci/JSONViewer-for-Chrome#8]
I installed this extension from the Chrome store. It seems to be your [official distribution](https://chrome.google.com/webstore/detail/json-viewer/aimiinbnnkboelefkjlenlgimcabobli) as it's linked from this repo. 

In the changelog it says "v0.8.5 - Added Traffzila" and I just noticed the extension redirected traffic to traffzilla.xyz. I don't see any reference to this domain in the Github source. What is it please?

**Comment by timwhitlock** [comment]
I see now that it's the [with-referals](https://github.com/teocci/JSONViewer-for-Chrome/tree/with-referals) branch that is the version in the Chrome Web Store.

This version redirects about [25k domains](https://traffzilla.xyz/coverage?key=4d4d2708f61508192a1c4da6b238cc4c) through Traffzilla adding affiliate tracking IDs to the URL.

**Comment by teocci** [comment]
the version now is the version 0.8.5 and I added the Traffizilla if you
enter one of the host then traffzilla just register that you visit that
page the source code it is in the git.

**Comment by timwhitlock** [comment]
Why does a JSON viewer need to add affiliate tracking IDs to normal web pages I visit?

**Comment by teocci** [comment]
no it doesn't add anything to normal web pages. It only will register to traffzilla if you open one of the web in the list. I tested for one week before to add it to the extension. It is only available for 10% of the user if I find that many people complains about it I will remove it in the version 0.9.0.  Please check the source code if you thing that is malicious or something.

**Comment by timwhitlock** [comment]
> no it doesn't add anything to normal web pages.

Not accurate. If I visit 123-reg.co.uk (a normal web page) I get redirected through your affiliate tracker and back to 123-reg.co.uk with a bunch of extra data in the URL. Hence you have added data to my site visit that I did not add. Furthermore you have sent information about my browsing history to a third party without my consent.

>  I tested for one week before to add it to the extension.

Irrelevant.

> Please check the source code if you thing that is malicious or something.

I have checked the source code, that's how I know what it does.

**Comment by teocci** [comment]
> Not accurate.

As I told you **only when you access one page from the list of 25k domains** the traffzilla make the redirection if not if the URL is not in the list (normal page) will not do anything. 

In the case of the `123-reg.co.uk` this is the **4th element** from the 25k domains file. 

It is clear?

 I will add a disclaimer if is necessary.  Also as I said, this is in a testing mode for 10% of the users. If it cause some problem or inconveniences to the users. It will be removed in the version 0.8.5. This issue is still open

**Comment by timwhitlock** [comment]
I wasn't unclear. 

Add a disclaimer that you track visits to thousands of domains, then your users can decide whether to use your extension. I am now using a different one.

**Comment by Dentxinho** [comment]
I reported abuse on the Chrome Web Store

**Comment by teocci** [comment]
> Add a disclaimer that you track visits to thousands of domains, then your users can decide whether to use your extension. I am now using a different one.

I updated the extension 18 hour ago and I was testing if is not intrusive it is not a full deployed version. As I said, this is a simple script and the source is open it wasn't implemented before. if you want go back to the version 0.8.0 if this version is so annoying for you. Or use another extension. This issue will be close.
